### PR TITLE
Add default formatting

### LINKED ISSUE #101: Fix inconsistency in how spacing is handled by Checkstyle
@jpwalbran pointed out on Slack that Checkstyle isn't being super consistent about spacing around braces:

> I noticed a thing about the checkstyle. As part of some of the tests for lab 2, we’d have a line like
> 
> ```java
> queryParams.put("orderBy", Arrays.asList(new String[] {"body"}));
> ```
>
> This passes checkstyle fine. However,
>
> ```java
> queryParams.put("orderBy", Arrays.asList(new String[] { "body" }));
> ```
>
> This does not, because of the space between `{`  and `"body"`.
> The thing that I noticed was that
>
>  ```java
> queryParams.put("orderBy", Arrays.asList(new String[] {"body" }));
> ```
>
> also passes checkstyle, and I feel that it shouldn’t.

It's not our job to "fix Checkstyle", but it is weird that there is this inconsistency. I'm not 100% sure I "like" the brace/space rule anyway, so maybe we just remove that rule?

This would apply to almost all the subsequent labs, and [the iteration template](https://github.com/UMM-CSci-3601/3601-iteration-template/issues/791).

### LINKED ISSUE #112: Add default formatting on saving
This was proposed some time ago by @floogulinc [on the iteration template](https://github.com/UMM-CSci-3601/3601-iteration-template/issues/308) and I definitely think we want to do this. It might be nice to start here since that might be simpler and we can see what that looks like before wading into the swamp of doing it on the full project.

### PR DESCRIPTION
**Pull request by NicMcPhee**
This turns on `editor.formatOnSave` in VS Code, so that when files are saved they will be automatically reformatted to a shared standard formatting so we have consistent formatting across everyone's work on this lab.

I'm using the RedHat Java formatter and MarkdownLint for Markdown files.

It turned out that several of the Markdown files had some issues, so I fixed those and am committing them as well while I'm here.

Fixes #112 
Closes #101
- Because we don't need Checkstyle anymore, and the Java formatter seems to properly handle the case people were concerned about.

### CODE REVIEW

**Comment by kklamberty** [comment]
I have a concern that I don't have the time/brain cells to check about. Will there be files that are currently not following this formatting that will look like they've been changed (even if just in whitespace) if someone goes there and saves them? Is there any easy way to see if there are files that would currently be "fixed" upon saving, or is this similar enough to the checkstyle stuff that we are in the clear?

**Review by kklamberty — COMMENTED** [review]
I have a concern that I don't have the time/brain cells to check about. Will there be files that are currently not following this formatting that will look like they've been changed (even if just in whitespace) if someone goes there and saves them? Is there any easy way to see if there are files that would currently be "fixed" upon saving, or is this similar enough to the checkstyle stuff that we are in the clear?

**Comment by NicMcPhee** [comment]
If you switch to this branch and then do some "weird" things in VSCode, you can see it automatically "fix" them when you save.

As an example, there were concerns (#101) that Checkstyle wasn't being consistent about spacing around curly braces. So I tried things like:

```java
String[] strings = { "Hello", "world" };
```

If I remove the spaces between, for example, the open curly brace and "Hello" and save, the space will magically re-appear.

The RedHat Java formatter that I'm using here is less aggressive than the Prettier formatter.  Prettier changed the formatting in several other places in the Java code. In particular it reformatted the big strings in the tests so that each component was on its own line. We'll see that in action when I add Prettier to the iteration template.

Does that help?

**Review by kklamberty — DISMISSED** [review]
This looks good. I won't muck up this PR with this, but I noticed we say things in `KK_and_Nic.md` lines 11 and 18 that put our name preferences in the past tense. Not sure why we did that, but might be worth fixing. Also, do people say "preferred" pronouns these days, or just "My pronouns are..."? I feel like that has shifted over time and might be good to update.

**Comment by NicMcPhee** [comment]
Good point on the tense and phrasing. I'll make a new issue for that and see if I can get this guy merged in.

**Review by kklamberty — DISMISSED** [review]
Looks good!

**Review by kklamberty — APPROVED** [review]

**Pull request merged**
