### PR TITLE
Add CodeQL and DeepSource support

### PR DESCRIPTION
**Pull request by NicMcPhee**
This hopefully gets both CodeQL running (better) and DeepSource working (for the first time on this repo).

This sets the DeepSource runtime to be v17 of Java, as that's the most recent LTS version they support (at the moment). We actually using v21, but there's nothing in this project that uses fancy new features of Java, so we should be safe until DeepSource gets up to supporting v21.

### CODE REVIEW

**Comment by NicMcPhee** [comment]
I think this got CodeQL working, but DeepSource remains silent. That _may_ require doing something on their web site, and I think that @kklamberty needs to add me to a team on the DeepSource site for me to be able to do that.

**Comment by kklamberty** [comment]
I've emailed an invite to @NicMcPhee to be an administrator, and I also went ahead and added the repository. I was unable to activate it, though, since the toml file is not yet in the main branch (as shown here). I think that means once it's merged you still may need to activate it manually. I have left it as a setting to manually add repositories since we have quite a few repos that I don't think we will want activated.

Image 1-12-24 at 4 31 PM

**Comment by kklamberty** [comment]
> This sets the runtime to be v21 of Java, which is what we're using. Their docs (https://docs.deepsource.com/docs/analyzers-java#meta) suggest that they only support up to v19, though, so I'm not sure what will happen here.

It does seem like this is causing troubles. The DeepSource check says we have errors in the `.deepsource.toml`. I'm inclined to use the last LTS before 21 that is supported (so, 17). I think that the kind of things it's checking for will be mostly fine 
(even if it's imperfect).

**Review by kklamberty — APPROVED** [review]
Looks good!

**Pull request merged**
