### PR TITLE
Replace references to Slack with Discord

### LINKED ISSUE #117: Replace references to Slack with references to Discord
The world appears to have moved from Slack to Discord (at least for now), so we need to catch references to Slack and change them.

### PR DESCRIPTION
**Pull request by NicMcPhee**
There were only two, and I actually only replaced one of them. For the other, Slack was in a list of tools using Markdown, so it made sense to leave it, although I did actually add Discord as well.

Closes #117

### CODE REVIEW

**Comment by NicMcPhee** [comment]
My guess is that this will have a conflict with #119, but it should be pretty easy for me to resolve if `git`/GitHub can't do it for us.

**Review by kklamberty — APPROVED** [review]
I think that the part in lines 500-504 was needing to be spaced differently so that I could resolve the conflict since it's special formatting. If you want to resolve that conflict some other way and have the spacing be exactly right, please feel free.

**Comment by kklamberty** [comment]
> Actually, we don't _want_ to resolve that conflict – it's there as an example. I think that adding the leading spaces might be a "good" thing in that it still looks fine when you're reading the Markdown file, but GitHub might not try to interpret it as a conflict to be resolved?

I should have said that I was trying to *mark* that conflict as resolved. GitHub was not letting me merge it if I left it exactly as it was because it was seeing that as a conflict. Granted... I was editing it right in GitHub, so that may have looked different if I was editing it elsewhere. I added the spaces and left everything else as it was so that the example would be preserved as much as I could.

**Comment by NicMcPhee** [comment]
I think I'm kind of baffled, actually. I think everything is fine, though?

**Pull request merged**
